name: Collect

on:
  push:
    branches: [ "main" ]
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  collect-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: '3.10'
      - name: Prepare
        run: pip3 install -r requirement.txt
      - name: Crawler
        run: python3 main.py ${{ secrets.CUSTOMS_GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: result.json
          path: result.json

